### ISSUE TITLE
关于branch coverage

### ISSUE THREAD

**Issue by yanglimingcn** [PennaLai/bazel_branch_coverage#1]
我是一个bazel新手，我最近用3.7版本的bazel coverage生产测试报告，发现没有办法产生分支覆盖率。请问3.7是本来就不支持吗？较新的版本支持吗？
不吝赐教

**Comment by PennaLai** [comment]
bazel 0.24.0版本后，因为gcov偶现的core的问题，默认将gcov -b去掉了，所以我这里修改了一下相关配置重新编译了bazel，你用这个替换原来的bazel应该是可以得到分支覆盖率的

**Comment by yanglimingcn** [comment]
我这边的环境，和你编译的环境不同，报
./bazel-real: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.23' not found (required by ./bazel-real)
./bazel-real: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ./bazel-real)
./bazel-real: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by ./bazel-real)
c++库不对，你能否把修改也提交上来，我看看呢？

**Comment by PennaLai** [comment]
下载bazel的源码，打开tools/test/collect_cc_coverage.sh
把第126行从下面1修改成2

"${GCOV}" -i $COVERAGE_GCOV_OPTIONS -o "$(dirname ${gcda})" "${gcda}"

"${GCOV}" -i -b $COVERAGE_GCOV_OPTIONS -o "$(dirname ${gcda})" "${gcda}"
重新编译即可


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PennaLai/bazel_branch_coverage"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月30日(星期一) 下午2:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PennaLai/bazel_branch_coverage] 关于branch coverage (#1)





 
我这边的环境，和你编译的环境不同，报
 ./bazel-real: /lib64/libstdc++.so.6: version GLIBCXX_3.4.23' not found (required by ./bazel-real) ./bazel-real: /lib64/libstdc++.so.6: version CXXABI_1.3.8' not found (required by ./bazel-real)
 ./bazel-real: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by ./bazel-real)
 c++库不对，你能否把修改也提交上来，我看看呢？
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yanglimingcn** [comment]
好的，我试试，谢谢您。

**Comment by yanglimingcn** [comment]
可以bazel coverage --action_env=COVERAGE_GCOV_OPTIONS=-b 这样加个选项，就不需要重新编译bazel了。
